### ISSUE TITLE
Filepress

### ISSUE THREAD

**Issue by pk3011** [missemily22/MultiFunctionBot#17]
[09-Dec-22 12:46:34 - INFO] - pyrogram.dispatcher - Started 5 HandlerTasks
[09-Dec-22 12:49:14 - INFO] - bot.plugins.users.gdfv -  Received : /gd@byp_bot - https://filepress.online/file/6392fe570d77d23523a47b73
[09-Dec-22 12:49:16 - ERROR] - pyrogram.dispatcher - It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/helpers/decorators.py", line 22, in decorator
    return await func(client, message)
  File "/usr/src/app/bot/plugins/users/gdfv.py", line 163, in gd
    res = await filepress(url)
  File "/usr/src/app/bot/modules/gdrive_direct.py", line 298, in filepress
    with sync_playwright() as playwright:
  File "/usr/local/lib/python3.10/dist-packages/playwright/sync_api/_context_manager.py", line 44, in __enter__
    raise Error(
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead

**Comment by missemily22** [comment]
@pk3011 Thanks 
I will be searching for fix
